#!/usr/bin/env bash
set -euo pipefail

: "${PROJECT_ID:?set PROJECT_ID}"
: "${REGION:?set REGION}"
: "${IMAGE:?set IMAGE}"
: "${OAUTH_ISSUER_URI:?set OAUTH_ISSUER_URI}"
: "${KAFKA_BOOTSTRAP_SERVERS:?set KAFKA_BOOTSTRAP_SERVERS}"
: "${REDIS_HOST:?set REDIS_HOST}"
: "${OPENSEARCH_URL:?set OPENSEARCH_URL}"

EMBEDDING_MODEL=${EMBEDDING_MODEL:-gemini-embedding-001}
EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION:-768}
EMBEDDING_LOCATION=${EMBEDDING_LOCATION:-us-central1}

gcloud config set project "$PROJECT_ID"

COMMON_ENV="EMBEDDING_PROVIDER=vertex,EMBEDDING_PROJECT_ID=$PROJECT_ID,EMBEDDING_LOCATION=$EMBEDDING_LOCATION,EMBEDDING_MODEL=$EMBEDDING_MODEL,EMBEDDING_DIMENSION=$EMBEDDING_DIMENSION,OPENSEARCH_URL=$OPENSEARCH_URL"

gcloud run deploy document-search-api \
  --image "$IMAGE" \
  --region "$REGION" \
  --allow-unauthenticated \
  --ingress internal-and-cloud-load-balancing \
  --min 2 \
  --max 100 \
  --concurrency 80 \
  --set-env-vars "SPRING_PROFILES_ACTIVE=api,SECURITY_ENABLED=true,SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=$OAUTH_ISSUER_URI,KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS,REDIS_HOST=$REDIS_HOST,$COMMON_ENV"

gcloud run worker-pools deploy document-search-indexer \
  --image "$IMAGE" \
  --region "$REGION" \
  --instances 2 \
  --set-env-vars "SPRING_PROFILES_ACTIVE=indexer,KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS,OPENSEARCH_REPLICAS=1,$COMMON_ENV"
